baseURL = "https://mecattaf.dev/"
languageCode = "en-us"
title = "メカタフ"
copyright = "Creative Commons BY 3.0"
theme = "thomas"
pygmentsCodeFences = true

[permalinks]
	blog = "/blog/:year/:slug/"

[params.author]
	name = "Thomas Mecattaf"

[taxonomies]
	tag = "tags"

[outputs]
	home = ["HTML"]
	section = ["HTML"]

[markup.goldmark.renderer]
	unsafe = true
