image: archlinux
packages:
  - hugo
  - rsync
  - npm
  - go
secrets:
  - 77c7956b-003e-44f7-bb5c-2944b2047654 # SSH deploy key
sources:
  - https://git.sr.ht/~emersion/emersion.fr
tasks:
  - setup: |
      cd emersion.fr/themes/shimong/static
      npm install
  - openring: |
      cd emersion.fr
      ./openring-update.sh
  - build: |
      cd emersion.fr
      hugo
  - upload: |
      cd emersion.fr/public
      [ "$(git rev-parse origin/master)" = "$(git rev-parse HEAD)" ] || complete-build
      rsync --rsh="ssh -o StrictHostKeyChecking=no" -rP \
          --delete --delete-excluded \
          . deploy@sheeta.emersion.fr:/srv/http/emersion.fr
triggers:
  - action: email
    condition: failure
    to: "<contact@emersion.fr>"
